version: '3.8'

services:
  db:
    container_name: db
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
      - static_volume:/star-burger/backend/static
      - bundles_volume:/star-burger/bundles
    depends_on:
      - db

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: sh -c "python /star-burger/backend/manage.py migrate &&
      python /star-burger/backend/manage.py collectstatic --no-input --clear &&
      python /star-burger/backend/manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/star-burger/
      - static_volume:/star-burger/backend/static
      - media_volume:/star-burger/backend/media
      - bundles_volume:/star-burger/backend/bundles
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume:
  bundles_volume:
